# Generated by Django 4.2.14 on 2024-10-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alcoholtype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='servingglass',
            options={'ordering': ['name'], 'verbose_name': 'Serving Glass', 'verbose_name_plural': 'Serving Glasses'},
        ),
        migrations.AlterField(
            model_name='alcoholtype',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='drink',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
