# Generated by Django 4.2.14 on 2024-10-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_alcoholtype_options_alter_servingglass_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flavorprofile',
            options={'ordering': ['profile']},
        ),
        migrations.AddField(
            model_name='garnish',
            name='measurement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
