# Generated by Django 4.2.5 on 2023-09-18 02:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_drinkrecipe_base_alcohol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientname',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=5, null=True),
        ),
    ]
