# Generated by Django 4.2.14 on 2024-10-05 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_flavorprofile_options_garnish_measurement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='garnish',
            options={'ordering': ['name'], 'verbose_name': 'Garnish', 'verbose_name_plural': 'Garnishes'},
        ),
        migrations.AlterUniqueTogether(
            name='garnish',
            unique_together={('name', 'measurement', 'value')},
        ),
    ]
