# Generated by Django 4.2.14 on 2024-10-31 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_garnish_options_alter_garnish_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavorprofile',
            name='profile',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
