# Generated by Django 4.2.5 on 2024-04-26 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_ingredientname_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='garnish',
            options={'ordering': ['name'], 'verbose_name': 'Garnish', 'verbose_name_plural': 'Garnishes'},
        ),
        migrations.AlterModelOptions(
            name='ingredientname',
            options={'ordering': ['ingredient']},
        ),
    ]
