# Generated by Django 4.2.5 on 2024-04-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_garnish_options_alter_ingredientname_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='alcoholtype',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
    ]
