# Generated by Django 4.2.5 on 2024-04-28 00:12

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_drink_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkrecipe',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, verbose_name=base.models.Drink),
        ),
        migrations.AlterField(
            model_name='drinkrecipe',
            name='ingredient_name',
            field=models.ManyToManyField(blank=True, related_name='ingredient_list', to='base.ingredientname'),
        ),
    ]
