# Generated by Django 4.2.5 on 2024-04-29 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_drinkrecipe_drink_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkrecipe',
            name='slug',
            field=models.SlugField(default='None', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drinkrecipe',
            name='serving_glass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='serving_glass', to='base.servingglass'),
        ),
    ]
