# Generated by Django 4.2.5 on 2024-04-29 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_alcoholtype_slug_alter_drink_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinkrecipe',
            name='slug',
        ),
        migrations.AlterField(
            model_name='alcoholtype',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='drink',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
    ]
