# Generated by Django 4.2.5 on 2024-04-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_drinkrecipe_slug_alter_alcoholtype_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkrecipe',
            name='must_know_drink',
            field=models.BooleanField(default=False),
        ),
    ]
