# Generated by Django 4.2.5 on 2024-05-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_drinkrecipe_must_know_drink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
