# Generated by Django 4.2.5 on 2024-05-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_alcoholtype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkrecipe',
            name='top_hundred_drink',
            field=models.BooleanField(default=False),
        ),
    ]
